export const Fonts = {
  titleThin: 'Montserrat_100Thin',
  titleExtraLight: 'Montserrat_200ExtraLight',
  serifLight: 'CormorantGaramond_300Light',
  serifRegular: 'CormorantGaramond_400Regular',
  serifMedium: 'CormorantGaramond_500Medium',
  serifSemiBold: 'CormorantGaramond_600SemiBold',
  serifBold: 'CormorantGaramond_700Bold',
  serifLightItalic: 'CormorantGaramond_300Light_Italic',
  italic: 'CormorantGaramond_400Regular_Italic',
  italicMedium: 'CormorantGaramond_500Medium_Italic',
  italicSemiBold: 'CormorantGaramond_600SemiBold_Italic',
  titleLight: 'Montserrat_300Light',
  titleRegular: 'Montserrat_400Regular',
  titleMedium: 'Montserrat_500Medium',
  titleSemiBold: 'Montserrat_600SemiBold',
  titleBold: 'Montserrat_700Bold',
};
